### PR TITLE
CPU info for Raspberry Pi 4B

### PR DESCRIPTION
**Pull request by chetbox**
This was taken from a 64 Raspberry Pi OS installation on a Raspberry Pi 4B.

### CODE REVIEW

**Comment by pguyot** [comment]
Thanks. Can we use fake serial `676974687562004b` ("github" 00 4b) instead of a real (realistic?) CPU ID?

**Comment by chetbox** [comment]
Sure thing! Done.

**Comment by chetbox** [comment]
Hi @pguyot!
Do you plan to make a release with the latest changes?

**Comment by pguyot** [comment]
Thanks for the nudge!

**Comment by chetbox** [comment]
Thank you! :)

**Pull request merged**
