### PR TITLE
Tests for new shell enhancements

### PR DESCRIPTION
**Pull request by twojstaryzdomu**

### CODE REVIEW

**Comment by twojstaryzdomu** [comment]
Note: before these get included in this repository, make sure these tests reference the right repository (under uses: in each file).

**Comment by pguyot** [comment]
Could you please fix the repository reference in test cases so this can be merged?

**Comment by twojstaryzdomu** [comment]
Done, please merge, I have a PR for #12 in the pipeline in the shell & test branches.

**Comment by pguyot** [comment]
This is nice, thanks. However, I would like to eventually get each PR squashed into a single commit with tests passing.
Could you please remove the custom URL test from this PR? Could you please also rebase PR #12 and include the custom URL test, referring to this project? (it's ok if tests do not pass in the PR because of this reference).

**Comment by twojstaryzdomu** [comment]
All right, removed custom URL tests. By the way, the project does not include a license, can you add one please? I'd like to publish a github action based on your code that builds debian packages and publishes them on github. It's not possible to call a github action in a github action so it relies in parts on some of your code.

**Pull request merged**
